# Введение в нейронные сети
## Фреймворк PyTorch
- <https://pytorch.org/docs/stable/index.html>

In [1]:
import torch

In [2]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([2, 3, 4])

In [3]:
x * y

tensor([ 2,  6, 12])

In [4]:
x @ y

tensor(20)

In [5]:
x = torch.tensor([1, 2, 3], dtype=torch.float32, requires_grad=True)
y = torch.tensor([2, 3, 4], dtype=torch.float32, requires_grad=True)
z = x @ y
z.backward()
x.grad, y.grad

(tensor([2., 3., 4.]), tensor([1., 2., 3.]))

In [6]:
x = torch.tensor([1, 2, 3], dtype=torch.float32, requires_grad=True)
y = torch.tensor([1, 3, 1], dtype=torch.float32)

In [7]:
loss = ((x - y) ** 2).sum()
loss

tensor(5., grad_fn=<SumBackward0>)

In [8]:
loss.backward()
x.grad, 2 * (x - y)

(tensor([ 0., -2.,  4.]), tensor([ 0., -2.,  4.], grad_fn=<MulBackward0>))

In [9]:
w = torch.randn((1, 10), requires_grad=True)
b = torch.randn(1, requires_grad=True)
X = torch.randn((100, 10))
y = torch.randint(0, 1, size=(100, 1), dtype=torch.float32)

In [10]:
y_pred = (X @ w.T + b).sigmoid()

In [11]:
criterion = torch.nn.BCELoss()
loss = criterion(y_pred, y)
print(loss)
loss.backward()

tensor(1.3507, grad_fn=<BinaryCrossEntropyBackward0>)


In [12]:
w.grad, b.grad

(tensor([[ 0.0571,  0.1025,  0.1058,  0.0500,  0.0850, -0.0688,  0.1814, -0.0660,
          -0.0637, -0.0489]]),
 tensor([0.5849]))

In [13]:
w = torch.randn((1, 10), requires_grad=True)
b = torch.randn(1, requires_grad=True)

for i in range(X.shape[0]):
    y_pred = (X[i] @ w.T + b).sigmoid()
    loss = criterion(y_pred, y[i])
    loss.backward()
    
    w.data -= 0.1 * w.grad
    b.data -= 0.1 * b.grad
    w.grad.zero_()
    b.grad.zero_()

In [14]:
y_pred = (X @ w.T + b).sigmoid()
loss = criterion(y_pred, y)
print(loss)

tensor(0.1600, grad_fn=<BinaryCrossEntropyBackward0>)
